[package]
name = "trace"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
vtracer = "0.6"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
fileio = { path = "../fileio" }
